[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | Docker
  | maintenance-scripts
)/
'''

[tool.isort]
profile = "black"
line_length = 79
