on:
    release:
        types: [published]

jobs:
    release-production:
        name: Release to production
        if: startsWith(github.ref_name,'r-')
        environment: production
        runs-on: ${{matrix.os}}
        env:
            DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
            PASSWORD_SCORING_APP: ${{secrets.PASSWORD_SCORING_APP}}
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: ['3.11','3.12']
        steps:
        - name: deploy application image on production environment
          run: |
            echo "${{ secrets.SSH_DEV_SERVER_CONTABO }}" > ~/work/_temp/dev_server_rsa
            chmod 400 ~/work/_temp/dev_server_rsa
            ssh -o StrictHostKeyChecking=no -i ~/work/_temp/dev_server_rsa ${{secrets.SERVER_ADMIN_PROD}}@${{secrets.SERVER_HOSTNAME_PROD}} "
                docker login -u $DOCKER_USER -p $DOCKER_PASS && 
                source .profile &&
                cd $PASSWORD_SCORING_APP &&
                ./stop_container.sh &&
                ./start_container.sh"
            rm -f ~/work/_temp/dev_server_rsa
            rm -rf ~/work/_temp