version: '3.8'
services:
  app_password_scoring_container:
    container_name: app_password_scoring_container
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:ws-password-scoring-${APP_VERSION}
    restart: always
    ports:
      - 6019:6019
    networks:
      - password-scoring-bridge
    env_file:
      - .env
      - .env.keys
      - .env.app.version

networks:
  password-scoring-bridge:
    driver: bridge